apiVersion: palette.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: spectrocloud-default-creds
      namespace: crossplane-system
      key: credentials