apiVersion: palette.crossplane.io/v1alpha1
kind: PasswordPolicy
metadata:
  name: demo-cp-password-policy
spec:
  forProvider:
    firstReminderDays: 5
    minDigits: 1
    minLowercaseLetters: 5
    minPasswordLength: 6
    minSpecialCharacters: 1
    minUppercaseLetters: 1
    passwordExpiryDays: 365
