apiVersion: palette.crossplane.io/v1alpha1
kind: AWSCluster
metadata:
  name: demo-cp-aws-01
spec:
  forProvider:
    context: project
    cloudAccountId: "FILL ME IN"
    cloudConfig:
    - region: "FILL ME IN"
      sshKeyName: "FILL ME IN"
    clusterProfile:
    - id: "FILL ME IN"
    machinePool:
    - additionalLabels:
        owner: crossplane
      controlPlane: true
      controlPlaneAsWorker: false
      count: 1
      diskSizeGb: 60
      instanceType: m5.xlarge
      name: cp-pool
    - additionalLabels:
        owner: crossplane
      count: 2
      instanceType: m5.xlarge
      name: worker-basic
    name: demo-cp-aws-01
    tags:
    - owner:crossplane
