apiVersion: palette.crossplane.io/v1alpha1
kind: EKSCluster
metadata:
  name: demo-cp-eks-cls-01
spec:
  forProvider:
    cloudAccountId: "FILL ME IN"
    context: tenant
    cloudConfig:
    - region: "FILL ME IN"
      sshKeyName: "FILL ME IN"
    clusterProfile:
    - id: "FILL ME IN"
    machinePool:
    - count: 3
      diskSizeGb: 60
      instanceType: t3.large
      name: worker-basic
    name: demo-cp-eks-cls-01