apiVersion: palette.crossplane.io/v1alpha1
kind: AzureCluster
metadata:
  name: demo-cp-azure-01
spec:
  forProvider:
    cloudAccountId: "FILL ME IN"
    context: tenant
    cloudConfig:
    - region: "FILL ME IN"
      resourceGroup: "FILL ME IN"
      sshKey: "FILL ME IN"
      subscriptionId: "FILL ME IN"
    clusterProfile:
    - id: "FILL ME IN"
    machinePool:
    - controlPlane: true
      controlPlaneAsWorker: true
      count: 1
      disk:
      - sizeGb: 65
        type: Standard_LRS
      instanceType: Standard_D4_v3
      name: cp-pool
    - count: 2
      instanceType: Standard_D4_v3
      name: worker-basic
    name: demo-cp-azure-01
    tags:
    - owner:crossplane
