apiVersion: palette.crossplane.io/v1alpha1
kind: AKSCluster
metadata:
  name: demo-cp-aks-01
spec:
  forProvider:
    context: project
    cloudAccountId: "FILL ME IN"
    cloudConfig:
    - region: "FILL ME IN"
      resourceGroup: "FILL ME IN"
      sshKey: "FILL ME IN"
      subscriptionId: "FILL ME IN"
    clusterProfile:
    - id: "FILL ME IN"
    machinePool:
    - count: 2
      diskSizeGb: 60
      instanceType: Standard_A4_V2
      isSystemNodePool: true
      name: worker-pool
      storageAccountType: Standard_LRS
    name: demo-cp-aks-01
    tags:
    - "owner:crossplane"
