apiVersion: palette.crossplane.io/v1alpha1
kind: GCPCluster
metadata:
  name: demo-cp-gcp-01
spec:
  forProvider:
    cloudAccountId: "FILL ME IN"
    cloudConfig:
    - project: "FILL ME IN"
      region: us-east1
    clusterProfile:
    - id: "FILL ME IN"
    machinePool:
    - controlPlane: true
      controlPlaneAsWorker: false
      count: 1
      diskSizeGb: 60
      instanceType: e2-standard-4
      name: cp-pool
      azs:
      - us-east1-d
      - us-east1-b
      - us-east1-c
    - count: 2
      instanceType: e2-standard-2
      name: worker-basic
      diskSizeGb: 60
      azs:
      - us-east1-d
      - us-east1-b
      - us-east1-c
    name: demo-cp-gcp-01
    tags:
    - owner:scott
