apiVersion: palette.crossplane.io/v1alpha1
kind: GKECluster
metadata:
  name: demo-cp-gke-01
spec:
  forProvider:
    name: demo-cp-gke-01
    cloudAccountId: "FILL ME IN"
    context: project
    osPatchOnBoot: false
    pauseAgentUpgrades: lock
    skipCompletion: false
    tags:
    - owner:crossplane
    cloudConfig:
      - project: "FILL ME IN"
        region: "FILL ME IN"
    clusterProfile:
      - id: "FILL ME IN"
        variables: {}
    machinePool:
      - name: basic-workers
        count: 3
        diskSizeGb: 60
        instanceType: c2d-standard-4
        updateStrategy: RollingUpdateScaleOut
        additionalLabels: {}