apiVersion: palette.crossplane.io/v1alpha1
kind: VirtualCluster
metadata:
  name: demo-cp-vcluster-01
spec:
  forProvider:
    clusterGroupUid: "FILL ME IN"
    context: project
    name: demo-cp-vcluster-01
    resources:
    - maxCpu: 4
      maxMemInMb: 6000
      minCpu: 0
      minMemInMb: 0
