apiVersion: palette.crossplane.io/v1alpha1
kind: VSphereCluster
metadata:
  name: demo-cp-vsphere-01
spec:
  forProvider:
    cloudAccountId: "FILL ME IN"
    context: tenant
    name: demo-cp-vsphere-01
    osPatchOnBoot: false
    skipCompletion: false
    cloudConfig:
      - datacenter: "FILL ME IN"
        folder: "FILL ME IN"
        imageTemplateFolder: "FILL ME IN"
        ntpServers: 
          - "FILL ME IN"
        sshKeys:
          - "FILL ME IN"
        staticIp: true
    clusterProfile:
      - id: "FILL ME IN"
        variables: {}
      - id: "FILL ME IN"
        variables: {}
      - id: "FILL ME IN"
        variables: {}
    machinePool:
      - controlPlane: false
        controlPlaneAsWorker: false
        count: 4
        name: worker-pool
        instanceType:
          - cpu: 8
            diskSizeGb: 60
            memoryMb: 16384
        placement:
          - cluster: "FILL ME IN"
            datastore: "FILL ME IN"
            network: "FILL ME IN"
            resourcePool: "FILL ME IN"
            staticIpPoolId: "FILL ME IN"
      - controlPlane: true
        controlPlaneAsWorker: false
        count: 1
        name: control-plane-pool
        instanceType:
          - cpu: 8
            diskSizeGb: 60
            memoryMb: 16384
        placement:
          - cluster: "FILL ME IN"
            datastore: "FILL ME IN"
            network: "FILL ME IN"
            resourcePool: "FILL ME IN"
            staticIpPoolId: "FILL ME IN"