// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AKSCluster) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ApplicationProfile) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AWSCloudAccount) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AWSCluster) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AzureCloudAccount) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AzureCluster) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BackupStorageLocation) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClusterGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClusterProfile) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CustomCloudAccount) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CustomCloudCluster) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DeveloperSetting) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EKSCluster) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Filter) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GCPCloudAccount) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GCPCluster) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GKECluster) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HelmRegistry) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MAASCloudAccount) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Macros) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OCIRegistry) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PasswordPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PlatformSetting) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PrivateCloudGatewayDNSMap) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PrivateCloudGatewayIPPool) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Project) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RegistrationToken) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ResourceLimit) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Role) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SSHKey) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Team) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *User) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VirtualCluster) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VSphereCloudAccount) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VSphereCluster) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Workspace) Hub() {}
