apiVersion: palette.crossplane.io/v1alpha1
kind: AWSCloudAccount
metadata:
  annotations:
    meta.upbound.io/example-id: palette/v1alpha1/awscloudaccount
  labels:
    testing.upbound.io/example-name: aws-1
  name: aws-1
spec:
  forProvider:
    awsAccessKey: ${var.aws_access_key}
    awsSecretKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    name: aws-1
