apiVersion: palette.crossplane.io/v1alpha1
kind: GKECluster
metadata:
  annotations:
    meta.upbound.io/example-id: palette/v1alpha1/gkecluster
  labels:
    testing.upbound.io/example-name: cluster
  name: cluster
spec:
  forProvider:
    cloudAccountId: ${data.spectrocloud_cloudaccount_gcp.account.id}
    cloudConfig:
    - project: ${var.gcp_project}
      region: ${var.gcp_region}
    clusterProfile:
    - id: ${data.spectrocloud_cluster_profile.profile.id}
    context: project
    description: Gke Cluster
    machinePool:
    - count: 3
      instanceType: n2-standard-4
      name: worker-basic
    name: ${var.cluster_name}
    tags:
    - dev
    - department:pax
    updateWorkerPoolInParallel: true
