apiVersion: palette.crossplane.io/v1alpha1
kind: HelmRegistry
metadata:
  annotations:
    meta.upbound.io/example-id: palette/v1alpha1/helmregistry
  labels:
    testing.upbound.io/example-name: r1
  name: r1
spec:
  forProvider:
    credentials:
    - credentialType: noAuth
      password: def
      username: abc
    endpoint: https://123456.dkr.ecr.us-west-1.amazonaws.com
    isPrivate: true
    name: us-artifactory
