apiVersion: palette.crossplane.io/v1alpha1
kind: OCIRegistry
metadata:
  annotations:
    meta.upbound.io/example-id: palette/v1alpha1/ociregistry
  labels:
    testing.upbound.io/example-name: r1
  name: r1
spec:
  forProvider:
    credentials:
    - arn: arn:aws:iam::123456:role/stage-demo-ecr
      credentialType: sts
      externalId: sofiwhgowbrgiornM=
    endpoint: 123456.dkr.ecr.us-west-1.amazonaws.com
    isPrivate: true
    name: test-nik2
    type: ecr
