apiVersion: palette.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: palette/v1alpha1/project
  labels:
    testing.upbound.io/example-name: project
  name: project
spec:
  forProvider:
    name: dev1
