apiVersion: palette.crossplane.io/v1alpha1
kind: SSHKey
metadata:
  annotations:
    meta.upbound.io/example-id: palette/v1alpha1/sshkey
  labels:
    testing.upbound.io/example-name: ssh_tenant
  name: ssh-tenant
spec:
  forProvider:
    context: project
    name: ssh-dev-1
    sshKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
