#! apiVersion: v1
#! kind: Secret
#! metadata:
#!   name: demo-cp-ssh-secret
#!   namespace: crossplane-system
#! type: Opaque
#! stringData:
#!   public-key: "FILL ME IN"
#! ---
apiVersion: palette.crossplane.io/v1alpha1
kind: SSHKey
metadata:
  name: demo-cp-ssh-key
spec:
  forProvider:
    context: project
    name: ssh-dev-1
    sshKeySecretRef:
      key: public-key
      name: demo-cp-ssh-secret
      namespace: crossplane-system
