apiVersion: palette.crossplane.io/v1alpha1
kind: AzureCloudAccount
metadata:
  name: demo-cp-azure-01
spec:
  forProvider:
    context: tenant
    cloud: AzurePublicCloud
    azureClientId: "FILL ME IN"
    azureClientSecretSecretRef:
      key: password
      name: demo-cp-azure-creds
      namespace: crossplane-system
    azureTenantId: "FILL ME IN"
    name: demo-cp-azure-01
#! ---
#! apiVersion: v1
#! kind: Secret
#! metadata:
#!   name: demo-cp-azure-creds
#!   namespace: crossplane-system
#! type: Opaque
#! stringData:
#!   password: "FILL ME IN"
