#! apiVersion: v1
#! kind: Secret
#! metadata:
#!   name: demo-cp-vultr-creds
#!   namespace: crossplane-system
#! type: Opaque
#! stringData:
#!   VULTR_API_KEY: "FILL ME IN"
#! ---
apiVersion: palette.crossplane.io/v1alpha1
kind: CustomCloudAccount
metadata:
  name: demo-cp-vultr
spec:
  forProvider:
    cloud: vultr
    context: tenant
    credentialsSecretRef:
      name: demo-cp-vultr-creds
      namespace: crossplane-system
    name: demo-cp-vultr
    privateCloudGatewayId: "FILL ME IN"
  initProvider:
    credentialsSecretRef:
      name: demo-cp-vultr-creds
      namespace: crossplane-system
