apiVersion: palette.crossplane.io/v1alpha1
kind: VSphereCloudAccount
metadata:
  name: demo-cp-vsphere-cloudaccount
spec:
  forProvider:
    context: tenant
    name: demo-cp-vsphere
    privateCloudGatewayId: "FILL ME IN"
    vsphereIgnoreInsecureError: true
    vspherePasswordSecretRef:
      key: password
      name: demo-cp-vsphere-creds
      namespace: crossplane-system
    vsphereUsername: "FILL ME IN"
    vsphereVcenter: "FILL ME IN"
#! ---
#! apiVersion: v1
#! kind: Secret
#! metadata:
#!   name: demo-cp-vsphere-creds
#!   namespace: crossplane-system
#! stringData:
#!   password: "FILL ME IN"