apiVersion: palette.crossplane.io/v1alpha1
kind: ClusterGroup
metadata:
  name: demo-cp-cluster-group-01
spec:
  forProvider:
    context: tenant
    clusters:
    - clusterUid: "FILL ME IN"
      hostDns: '*'
    config:
    - cpuMillicore: 6000
      hostEndpointType: LoadBalancer
      memoryInMb: 8192
      oversubscriptionPercent: 120
      storageInGb: 10
    name: demo-cp-cluster-group-01
