apiVersion: palette.crossplane.io/v1alpha1
kind: BackupStorageLocation
metadata:
  name: demo-cp-minio-bsl   
spec:
  forProvider:
    bucketName: demo-cp-minio-bucket
    context: tenant
    isDefault: false
    name: demo-cp-minio-bsl
    region: us-east-2
    storageProvider: minio
    s3:
    - accessKey: "FILL ME IN"
      credentialType: secret
      s3ForcePathStyle: true
      s3Url: "FILL ME IN"
      secretKey: "FILL ME IN"